on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      # GIT Checkout
      - uses: actions/checkout@v2

      # Cache node_modules
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Setup Node.JS
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Build
      - run: |
          cd ui
          npm ci
          npm run build
          echo $VUE_APP_COMMIT_HASH > dist/commit-hash.txt && cd .. && cp ota/version ui/dist/esp-version.txt

      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"

      # Deploy
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: ${( steps.branch.outputs.BRANCH_NAME }}
